timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
#domain: www.matchmakeredlabs.net
layout: default
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .vs/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "cards"
    values:
      layout: "card"
  -
    scope:
      path: ""
      type: "Solution"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "Action"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "About"
    values:
      layout: "default"
collections:
  cards:
    output: false
  Solution:
    output: true
    permalink: /Solution/:path.html
  Action:
    output: true
    permalink: /Action/:path.html
  About:
    output: true
    permalink: /About/:path.html
sass:
  sass_dir: _sass
