timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
#domain: www.matchmakeredlabs.net
layout: default
exclude:
  - README.md
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
