timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
#domain: www.matchmakeredlabs.net
layout: default
exclude:
  - README.md
  - docker-compose.yml
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "cards"
    values:
      layout: "card"
collections:
  cards:
    output: true
    permalink: /cards/:path.html
sass:
  sass_dir: _sass
